### ISSUE TITLE
Direct Export to tensorflow js

### ISSUE THREAD

**Issue by KartoffelToby** [lobe/web-bootstrap#14]
a lobe export Option to tensorflow js would be nice.

**Comment by adammenges** [comment]
Agreed! We'd love to add this and are evaluating when we could right now.

**Comment by KartoffelToby** [comment]
for now a working workflow to convert it would be nice. but this is related to #13

**Comment by KartoffelToby** [comment]
for now a working workflow to convert it would be nice. but this is related to #13

**Comment by kmanadkat** [comment]
I just tried to convert one & miserably failed. I did get model.json but the web code crashed badly.
1. I followed [tfjs-converter](https://github.com/tensorflow/tfjs/tree/master/tfjs-converter) as suggested in Docs. I assumed that the output of Lobe Export is **Tensorflow SavedModel** 
2. I got the model.json file (along with several bin files) with many warnings in terminal & there was no metadata.json file.

Please have a tensorflow js as the export option. Anyone can help for now?

<img width="1518" alt="Screenshot 2020-11-06 at 5 21 34 PM" src="https://user-images.githubusercontent.com/25281055/98363170-870c3d00-2054-11eb-87da-1df98b7bf488.png">

**Comment by ohjs88** [comment]
I don't understand why they made an example in a format that they couldn't extract.

**Comment by jlarmstrongiv** [comment]
After installing and using [`tensorflowjs_wizard`](https://github.com/tensorflow/tfjs/tree/master/tfjs-converter), the converter throws an error with `AssertionError: Got '4194304'`.

Has anyone had any luck converting to a tensorflow.js?  Any workaround, no matter how hacky, would be super helpful.

**Comment by mbeissinger** [comment]
We will have Lobe directly export TensorFlow.js soon! For now, you can use the conversion script here to go from the TensorFlow saved model exported by Lobe into TensorFlow.js: https://github.com/mbeissinger/tfjs-converter
