### ISSUE TITLE
web app 

### ISSUE THREAD

**Issue by quantum-fusion** [lobe/web-bootstrap#18]
I ran the web app, but it opens the camera, 

with 
Note
Thumbs down
Thumbs up

<img width="344" alt="Screen Shot 2021-03-28 at 9 10 23 AM" src="https://user-images.githubusercontent.com/10088099/112753391-73328a80-8fa5-11eb-8254-dc15823170dd.png">

It does not appear that the webcam detects anything.

What is this app supposed to do?  

What pictures/labels are loaded into the model?

**Comment by mbeissinger** [comment]
Hi! Glad you got the app running -- the model loaded by default is just a toy placeholder one I made. You should replace it with your own by selecting to Use > Export > TensorFlow.js in your Lobe project and dragging the exported model.json, signature.json, and all the *.bin files to the public/model/ folder here.

**Comment by quantum-fusion** [comment]
@mbeissinger Yes, but my question, is if I drag my model that detects Cars and Trucks, and it sees a video camera of my face with the webcam, then, what would be the expected result?  Would it be thumbs down?

**Comment by mbeissinger** [comment]
I would expect either a Car or Truck label -- the model is forced to pick one of the labels you supplied. They are being loaded from the signature.json file so make sure it also gets copied to the public/model folder from Lobe's TensorFlow.js export folder.

**Comment by quantum-fusion** [comment]
@mbeissinger I exported the model, and it now thinks that my face is a Truck. I am not sure that this is the intended behavior, but wonder if there might be a confidence level probability that might be able to be output.  I can see how this might run on a mobile phone if the app was deployed in the cloud.  Any ideas? 

<img width="313" alt="Screen Shot 2021-03-30 at 10 23 13 AM" src="https://user-images.githubusercontent.com/10088099/113004939-030d3b80-9142-11eb-82a5-44fbb2458ec1.png">

**Comment by mbeissinger** [comment]
@quantum-fusion great! This model is performing image classification (https://docs.lobe.ai/docs/welcome/welcome#what-is-image-classification) -- which means it will give one of your labels to every image passing through. If you want the model to predict that there isn't a car or truck, you need to add another label with examples of 'other' or 'none': https://docs.lobe.ai/docs/improving/improving#why-is-there-always-a-prediction-even-when-nothing-is-in-the-image

The width of the green bar is the confidence value -- and those confidence values are forced to sum to 1 across all your supplied labels. So this image looks something like 80% truck, 20% car based on the images you used to train the model. I would recommend to collect as many images you can to train Lobe, and evenly split them between truck, car, and none.

This starter project is for running your model as a browser-based web app to save money on server costs in the cloud. If you wanted to run your model as a prediction REST API, see our Flask server starter here: https://github.com/lobe/flask-server
