### ISSUE TITLE
After copy model  not working

### ISSUE THREAD

**Issue by tlraghavendra** [lobe/web-bootstrap#20]
Hi,

i manage to start Yarn and example project working fine. after i drag the model.json, signature.json, and all the *.bin files to the public/model/ folder, it is showing as "Loading". please advise

![image](https://user-images.githubusercontent.com/5299237/114384985-fd900680-9bc1-11eb-98da-eec886512948.png)

thanks in advance
Raghavendra

**Comment by mbeissinger** [comment]
Hi! What browser version are you using? How long did you wait for it to load?

**Comment by tlraghavendra** [comment]
i am using Google Chrome 90.0.4430.72. i did waited for 10 min. will that take more than that?

**Comment by tlraghavendra** [comment]
it seems my exported files got issue. after fresh export, it started working. 

thank you
