### ISSUE TITLE
lobe web-bootstrap never loads.

### ISSUE THREAD

**Issue by rcolepeterson** [lobe/web-bootstrap#24]
Cloned and deployed the web-bootstrap app on Netifly. Works.

I then updated model, tested locally, exported, re-deployed and it does not work.
Just loads for ever.

UI appears, no errors, but just loading text in bottom left. 

In console there is this message - **_imageClassificationModel.ts:112 Model not loaded, please await this.load() first._**

URL - https://naughty-bose-d279c2.netlify.app/

Any help would be great. If i cant get this to work online, I can't use it.

**Comment by mbeissinger** [comment]
Can you run the updated (latest export) model locally? Is it in the public/model folder and is the app looking in that folder? Double check by printing these values from https://github.com/lobe/web-bootstrap/blob/master/src/components/App.tsx#L14:

const signatureFile = process.env.PUBLIC_URL + /model/signature.json;
const modelFile = process.env.PUBLIC_URL + /model/model.json;

**Comment by rcolepeterson** [comment]
I don't think it is a pathing issue.
I think it is the size of the model issue. (again I am just doing a simple app for a test. hat / no hat).

Loads on www on "fast computers".
Does not load on "slow" computers.

Here is the test url ...
https://naughty-bose-d279c2.netlify.app/

https://naughty-bose-d279c2.netlify.app/model/signature.json
https://naughty-bose-d279c2.netlify.app/model/model.json

**Comment by rcolepeterson** [comment]
@mbeissinger do you have an example of the web version working online with something more than the hello world / thumbs up thumbs down example? Or does it just not work? and i should move on to a diff web solution? Thanks for your time.

**Comment by shreesha345** [comment]
I am also having the same issue please someone help me 😭

**Comment by mbeissinger** [comment]
Hi all! This should be fixed with #25, I tested using Netlify as well. Loaded the model on the predict() call if it wasn't done yet.

**Comment by mbeissinger** [comment]
To help with performance, I would recommend using the Speed model for your project because it is much smaller. (Menu > Project Settings > Optimize for Speed).
